## Aula 02 - Python

## Dados numéricos

In [4]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)


Valor de a = 1


int

In [5]:

# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [6]:
# Converter float para int
c = int(b)
print(c)
type(c)


1


int

In [7]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [8]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


## Dados de texto


In [9]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica



In [10]:

a == 1

True

In [11]:
h = (a==1)
print(h)
type(h)

True


bool

In [12]:
h = (a==2)
print(h)
type(h)

False


bool

In [13]:
i = True
type(i)

bool

In [14]:
ii = 'True'
type(ii)

str

## Operação de comparação

In [16]:
# Operação ==
a==b

True

In [17]:

# Operação ><
a>b

False

In [18]:
# Operação !=
a!=b

False

In [19]:
# Operação >= ou <=
a>=b

True

## Operações matemáticas


In [20]:
# Soma 
a+b

2.0

In [21]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [22]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [23]:
# Divisão
a/b

1.0

In [24]:
# Potencia
5**2

25

In [25]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [26]:
math.exp(0)

1.0

In [27]:
math.exp(a)

2.718281828459045

In [28]:
math.exp(-10)

4.5399929762484854e-05

In [29]:
import math as mt
mt.log(c)

0.0

In [30]:
mt.log10(100)

2.0

## Listas 

In [31]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [32]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [33]:
myFirstList==a

False

In [34]:
myFirstList[0]==a

True

In [35]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [36]:
type(mySecList)

list

In [37]:

type(mySecList[2])

str

In [38]:
type(mySecList[1])

int

## Caminhos = path

In [43]:
path = r"C:\Users\sergi\OneDrive\Documentos\GitHub\ENS5173_202401"
print(path)

C:\Users\sergi\OneDrive\Documentos\GitHub\ENS5173_202401


In [45]:
path = r"C:\Users\sergi\OneDrive\Documentos\GitHub\ENS5173_202401"
print(path)

C:\Users\sergi\OneDrive\Documentos\GitHub\ENS5173_202401


In [46]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'shapefile',
 'vend',
 'venv']

In [47]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [48]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:\\Users\\sergi\\OneDrive\\Documentos\\GitHub\\ENS5173_202401/.git'

In [49]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [50]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\sergi\\OneDrive\\Documentos\\GitHub\\ENS5173_202401\\venv\\Scripts'

In [55]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\sergi\\Documents\\')

In [56]:
os.getcwd()

'C:\\Users\\sergi\\Documents'

In [57]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\sergi\Documents/test


In [58]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\sergi\Documents/test2


## Numpy arrays e Pandas DataFrames

In [59]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [60]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [61]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.81045911 0.44813677 0.02997048 0.64345482 0.24222599 0.77579966
  0.81115283 0.3925947  0.65576618 0.57871493]
 [0.04521828 0.48071746 0.5652111  0.12939277 0.47904792 0.9021299
  0.13118688 0.82846959 0.20972121 0.6172571 ]
 [0.49967865 0.08114464 0.75092947 0.36763719 0.99580259 0.1974338
  0.6307924  0.87392048 0.72161934 0.90975592]
 [0.74213298 0.05306722 0.73713865 0.38672169 0.82865679 0.53390384
  0.55674916 0.7521603  0.14384133 0.47568445]
 [0.56695656 0.88511253 0.71517292 0.25993606 0.28198198 0.15813503
  0.54871922 0.9287687  0.90561839 0.22397563]
 [0.36905515 0.4637775  0.06488288 0.37931199 0.83717625 0.33218211
  0.19239799 0.23479356 0.16378568 0.6517253 ]
 [0.597906   0.67793253 0.19223443 0.63189841 0.57810042 0.38248993
  0.4017963  0.69111973 0.21358281 0.89572804]
 [0.90789617 0.63873835 0.18789167 0.57846368 0.77790602 0.73068369
  0.60438598 0.18528409 0.2982323  0.43139089]
 [0.62813511 0.75889975 0.31674979 0.78656706 0.38175115 0.30291248
  0.89252279 0

In [62]:
# Acessando valores da matriz
n[0,:]

array([0.81045911, 0.44813677, 0.02997048, 0.64345482, 0.24222599,
       0.77579966, 0.81115283, 0.3925947 , 0.65576618, 0.57871493])

In [63]:
n[:,0]

array([0.81045911, 0.04521828, 0.49967865, 0.74213298, 0.56695656,
       0.36905515, 0.597906  , 0.90789617, 0.62813511, 0.01025256])

In [64]:

n[:,1:5]

array([[0.44813677, 0.02997048, 0.64345482, 0.24222599],
       [0.48071746, 0.5652111 , 0.12939277, 0.47904792],
       [0.08114464, 0.75092947, 0.36763719, 0.99580259],
       [0.05306722, 0.73713865, 0.38672169, 0.82865679],
       [0.88511253, 0.71517292, 0.25993606, 0.28198198],
       [0.4637775 , 0.06488288, 0.37931199, 0.83717625],
       [0.67793253, 0.19223443, 0.63189841, 0.57810042],
       [0.63873835, 0.18789167, 0.57846368, 0.77790602],
       [0.75889975, 0.31674979, 0.78656706, 0.38175115],
       [0.92702909, 0.53942274, 0.6942686 , 0.42728286]])

In [65]:
n[0,1:5]

array([0.44813677, 0.02997048, 0.64345482, 0.24222599])

In [66]:

n[0,-1]

0.5787149320894572

In [68]:
n[0,4:-1]


array([0.24222599, 0.77579966, 0.81115283, 0.3925947 , 0.65576618])

In [69]:
n[0,4:]

array([0.24222599, 0.77579966, 0.81115283, 0.3925947 , 0.65576618,
       0.57871493])

In [70]:
an = np.log(n*5)
print(an)

[[ 1.39928352  0.80678112 -1.89810452  1.16853445  0.19155375  1.35557695
   1.40013912  0.67446042  1.18748692  1.06249264]
 [-1.48681596  0.87696233  1.03888192 -0.43546488  0.87348327  1.50644115
  -0.42169452  1.42126276  0.04746172  1.12696826]
 [ 0.91564782 -0.90208411  1.32299437  0.60877919  1.60523167 -0.01291403
   1.14865943  1.47467203  1.2831804   1.51485898]
 [ 1.31121107 -1.32675789  1.30445863  0.65938791  1.42148869  0.98189838
   1.02379743  1.3246321  -0.32960654  0.86643735]
 [ 1.04196532  1.48739742  1.27420699  0.26211829  0.3435258  -0.23486809
   1.0092695   1.53554237  1.51030065  0.11321986]
 [ 0.61262872  0.84108755 -1.12573363  0.6400417   1.43171726  0.50736598
  -0.03875128  0.16038929 -0.19975863  1.18130579]
 [ 1.09511619  1.2207304  -0.03960174  1.15041127  1.06143023  0.64838495
   0.69762787  1.23999571  0.06570727  1.49931947]
 [ 1.51281265  1.16117753 -0.06245179  1.06205839  1.35828835  1.29566329
   1.10589567 -0.07642709  0.39955535  0.76869725]
